config/routes.rb
Rails.application.routes.draw do
  root "films#index"
  get "/films", to: "films#index"

  scope "films" do
    get "video_file", to: "films#video_file", as: :film_video_file

    get "films/subtitle_file", to: "films#subtitle_file", as: :film_subtitle_file
    get "films/recommendation", to: "films#new_recommendation", as: :film_recommendation
    post "films/recommendation", to: "films#submit_recommendation", as: :submit_film_recommendation
    get '/recommendations', to: "films#show_recommendations", as: :recommendations
    post '/recommendation/:id/destroy', to: "films#destroy_recommendation", as: :destroy_recommendation

    get "films/upload", to: "films#upload", as: :upload_film
    post "films/chunk_create", to: "films#chunk_create", as: :chunk_create

    resources :films, except: [:new, :create]
    resources :unsynced_films, only: [:index]

    # This is done outside of resources because the :id passed here is actually a string
    # And it can cause issues when part of the URL
    get '/unsynced_film', to: "unsynced_films#show", as: :unsynced_film
    post '/force_create_unsynced_film', to: "unsynced_films#force_create", as: :force_create_film

    get "films/:id/watch", to: "films#watch", as: :watch_film

    # should be a post, but too lazy to convert link to form
    get '/unsynced_films/match', to: "unsynced_films#match_unsynced_film", as: :match_unsynced_film

    resources :tags, only: %i[create show]
    post 'tags/:id/remove', to: 'tags#remove', as: :remove_tag

    resources :comments, only: %i[create]
    post 'comments/:id/remove', to: "comments#remove", as: :remove_comment

    get 'info', to: "application#info", as: :info
  end
end

app/models/film.rb
# == Schema Information
#
# Table name: films
#
#  id          :bigint           not null, primary key
#  name        :string
#  year        :integer
#  description :text
#  director    :string
#  image_url   :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Film < ApplicationRecord
	has_many :film_taggings, dependent: :destroy
	has_many :tags, through: :film_taggings
	has_many :comments, dependent: :destroy

	def self.unsynced_film_names
		Storage.download_index_file.reject do |film_name|
			Film.exists?(name: film_name)
		end
	end

	def self.create_from_movie_db_lookup(folder_name, movie_db_results)
                `sudo sh /home/max/Desktop/VideoStreamer/scripts/rename_files.sh`
		film = Film.create!(
			name: folder_name.gsub(" ", "_"),
			description: movie_db_results[:details],
			year: DateTime.parse(movie_db_results[:date]).year,
			director: movie_db_results[:director],
			image_url: movie_db_results[:img_path],
		)
		movie_db_results[:genres].each do |genre|
			tag = Tag.find_or_create_by!(name: genre)
			FilmTagging.find_or_create_by!(film: film, tag: tag)
		end
		film
	end

	def size
		if super.nil?
	 		size_mb = files.sum { |file| file.size / 1_000_000.0 }
	 		update(size: size_mb)
 		end
 		super
	end

	def get_files
		Storage.get_files_in_folder(self.name)
	end
	alias files get_files

	def get_media_files
		video_formats = {
			".webm" => "video/webm",
			".mp4" => "video/mp4",
			".mpeg" => "video/mpeg",
			".mpg" => "video/mpeg",
			".ogg" => "video/ogg",
		}
		unsupported_video_formats = %w[.avi .mkv]
		subtitle_formats = %w[.srt .sub .vtt]

		files_by_extname = get_files.group_by { |file| File.extname(file.name) }

		{
			video: video_formats.each_with_object({}) do |(ext, media_type), memo|
				matches = files_by_extname[ext]
				next unless matches&.any?
				memo[media_type] ||= []
				memo[media_type].concat(matches)
			end,
			unsupported_video: unsupported_video_formats.flat_map do |ext|
				files_by_extname[ext] || []
			end,
			subtitle: subtitle_formats.flat_map do |ext|
				files_by_extname[ext] || []
			end
		}
	end
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_action :set_film, only: %i[ show edit update destroy watch]
  before_action :admin_only, only: %i[update edit destroy destroy_recommendation]

  def subtitle_file
    send_file Storage.local_file_path(params[:name]), type: "TextTrack"
  rescue => e
    if e.message == "file not accessible"
      head 404
    else
      raise
    end
  end

=begin
  def video_file
    send_file_with_range Storage.local_file_path(params[:name]), x_sendfile: true
  rescue => e
    if e.message == "file not accessible"
      head 404
    else
      raise
    end
  end

  def send_file_with_range(path, options = {})
    if File.exist?(path)
      size = File.size(path)
      if !request.headers["Range"]
        status_code = 200 # 200 OK
        offset = 0
        length = File.size(path)
      else
        status_code = 206 # 206 Partial Content
        bytes = Rack::Utils.byte_ranges(request.headers, size)[0]
        offset = bytes.begin
        length = bytes.end - bytes.begin
      end
      response.header["Accept-Ranges"] = "bytes"
      response.header["Content-Range"] = "bytes #{bytes.begin}-#{bytes.end}/#{size}" if bytes

      send_data IO.binread(path, length, offset), options
    else
      raise ActionController::MissingFile, "Cannot read file #{path}."
    end
  end
=end

  # GET /films or /films.json
  def index
    @all_directors = Film.distinct(:director).pluck(:director).compact.sort
    @all_tags = Tag.pluck(:name).sort_by(&:downcase)

    @films = Film.all
    @opts = {}

    if params[:director].present? && params[:director] != "all"
      @opts[:director] = params[:director]
      @films = @films.where(director: params[:director])
    end

    if params[:search]&.present?
        search = params[:search].gsub(" ", "_").downcase
	@films = @films.where("LOWER(name) LIKE ?", "%#{search}%")
    end

    if params[:tag].present? && params[:tag] != "all"
      @opts[:tag] = params[:tag]
      @films = @films.joins(film_taggings: :tag).where(tag: { name: params[:tag] })
    end

    @opts[:sort] = params[:sort]
    if params[:sort] == "date_asc"
      @films = @films.order(year: :asc)
    elsif params[:sort] == "date_desc"
      @films = @films.order(year: :desc)
    elsif params[:sort] == "size"
      @films = @films.order(size: :desc)
    elsif params[:sort] == "name"
      @films = @films.order(name: :asc)
    elsif params[:sort] == "newly_uploaded" || params[:sort].blank?
      @films = @films.order(created_at: :desc)
    end
  end

  def show_recommendations
    @recommendations = Recommendation.all
  end

  def new_recommendation
  end

  def destroy_recommendation
    @recommendation = Recommendation.find(params[:id])
    @recommendation.destroy!
    redirect_to :recommendations
  end

  def submit_recommendation
    Recommendation.create(sender: params[:sender], message: params[:message])
    flash[:notice] = "Your recommendation has been received"
    redirect_to :films  
  end

  def new
    @film = Film.new
  end

  def create
    @film = Film.create(film_params)
    `sudo sh /home/max/Desktop/VideoStreamer/scripts/rename_files.sh`
    @film.update(name: @film.name.gsub(" ", "_"))
    redirect_to @film
  end

  def watch
    @files = @film.get_media_files
    @vids = @files[:video]
    if params[:selected_video].present?
      selected_video = JSON.parse(params[:selected_video])
      @selected_video = {
        media_type: selected_video["media_type"],
        file: @vids.values.flatten.find { |vid| vid.name == selected_video["name"] }
      }
    end
    @subs = @files[:subtitle]
  end

  # GET /films/1 or /films/1.json
  def show
    @files = @film.get_media_files
  end

  # GET /films/1/edit
  def edit
  end

  # PATCH/PUT /films/1 or /films/1.json
  def update
    respond_to do |format|
      if @film.update(film_params)
        format.html { redirect_to film_url(@film), notice: "Film was successfully updated." }
        format.json { render :show, status: :ok, location: @film }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /films/1 or /films/1.json
  def destroy
    tags = @film.tags.to_a
    @film.destroy
    tags.each do |tag|
      if tag.films.none?
        tag.destroy!
      end
    end

    respond_to do |format|
      format.html { redirect_to films_url, notice: "Film was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_film
      @film = Film.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def film_params
      params.require(:film).permit(:name, :director, :year, :description, :image_url)
    end
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/views/films/_film_preview.html.slim
.film-box style="background: url('#{film.image_url}')"
  a.link-placeholder href=film_path(film)
  .film-title-bar
    .content
      / img.poster-img src=film.image_url
      / a href=film_path(film) = film.name
      p.film-name = film.name

      - year = film.year.present? ? film.year : "???"

      p
        a href=films_path(director: film.director) = film.director
        span = " (#{film.year})"

      - film.tags.each do |tag|
        a.tag href=films_path(tag: tag.name) = tag.name

      - if admin?
        br
        b = "Size: #{number_to_human_size film.size * 1_000_000}"

app/views/films/_form.html.slim
= form_with(model: @film) do |form|
  - if @film.errors.any?
    div style="color: red"
      h2 = "#{pluralize(@film.errors.count, "error")} prohibited this film from being saved:"
      ul
        - @film.errors.each do |error|
          li = error.full_message

  div
    = form.label :name, style: "display: block"
    = form.text_field :name

  div
    = form.label :description, style: "display: block"
    = form.text_area :description    

  div
    = form.label :director, style: "display: block"
    = form.text_field :director

  div
    = form.label :year, style: "display: block"
    = form.text_field :year

  div
    = form.label :image_url, style: "display: block"
    = form.text_field :image_url     

  div
    = form.submit
p
  strong Tags: 
  - if @film.tags.none?
    b =< "none"
  - else
    - @film.tags.each do |tag|
      ul
        li
          a href=tag_path(tag: tag.name) = tag.name
          span style='width: 10px; display: inline-block;'
          form style='display: inline-block' action=remove_tag_path(id: tag.id, film_id: @film.id) method="POST"
            input type='hidden' name='authenticity_token' value=form_authenticity_token
            input type='hidden' name='film_id' value=@film.id
            input type='hidden' name='id' value=tag.id
            input type='submit' value="Remove"

form action=tags_path(film: @film) method='POST'
  div
    input type='hidden' name='authenticity_token' value=form_authenticity_token
    input type='hidden' name='film_id' value=@film.id
    input type='text' name='name'
    br    
    input type='submit' value='Add Tag'

p
  strong Comments: 
  - if @film.comments.none?
    b =< "none"
  - else
    - @film.comments.each do |comment|
      ul
        li
          div.box
            span = "#{comment.author} (#{comment.created_at.strftime("%m/%d/%Y")}): "
            b = comment.content
            form action=remove_comment_path(id: comment.id) method='POST'
                  input type='hidden' name='authenticity_token' value=form_authenticity_token
                  input type='submit' value='Delete'
            

  form action=comments_path method='POST'
    input type='hidden' name='authenticity_token' value=form_authenticity_token
    input type='hidden' name='film_id' value=@film.id
    input type='text' name='author' placeholder='Your Name'
    br
    textarea name='content' placeholder='New Comment'
    br
    input type='submit' value='Add Comment'

app/views/films/edit.html.slim
h1 Editing film

== render "form", film: @film

br

div
  => link_to "Show this film", @film
  '|
  =< link_to "Back to films", films_path

app/views/films/index.html.slim
p style="font-weight: bold; color: white" = notice

#index-filters
  .index-filter
    b.filter-title Sort: 
    select#sort-select
      option name='sort' value='newly_uploaded' Newly Uploaded
      option name='sort' value='name' Name
      option name='sort' value='date_asc' Date (old to new)
      option name='sort' value='date_desc' Date (new to old)
      - if admin?
        option name='sort' value='size' Size

  .index-filter
    b.filter-title Director: 
    select#director-select
      option name='director' value='all' selected='true' All
      - @all_directors.each do |director|
        option name='director' value=director = director

  .index-filter
    b.filter-title Tag: 
    select#tag-select
      option name='tag' value='all' selected='true'  All
      - @all_tags.each do |tag|
        option name='tag' value=tag = tag

  .index-filter
    b.filter-title Search:
    input id='search-query' type='text' placeholder='search'
    button id='search' Search

  a.recommendation-link href=film_recommendation_path Recommend a film
  a.info-link href=info_path About this site
  a.info-link href='https://dissonant.info' Dissonant Info (Max Pleaner)


- if File.exists?(Rails.root.join("message.txt"))
  h1 style='color: red' = File.read(Rails.root.join("message.txt"))

#jellyfin
  h3.title Prefer a more fancy interface? - go to https://jellyfin.dissonant.info
  p
    b Note: the Jellyfin version supports in-browser streaming of more video formats than this version

  h3.title Jellyfin also works on Smart TVs!
  p
    b Instructions:
    span  ~ Download "Jellyfin app"
    span ~ Enter server name "https://jellyfin.dissonant.info"
    span ~ Use same username/password you use here.


#films
  - if admin?
    - total_size = @films.sum(&:size)
    h3 = "Total size: #{number_to_human_size total_size * 1_000_000}"
    h4 = "Cost per month: $#{((total_size / 1_000) / 50).round(1).to_s.ljust(4, "0")}"

  - @films.each do |film|
    = render "film_preview", film: film

coffeescript:
  $ =>
    urlParams = new URLSearchParams(window.location.search)

    director = urlParams.get("director")
    tag = urlParams.get("tag")
    sort = urlParams.get("sort")

    $("#sort-select")[0].value = sort if sort
    $("#tag-select")[0].value = tag if tag
    $("#director-select")[0].value = director if director

    $("#search").on "click", (e) =>
      path = "/films?search=" + $("#search-query").val()
      window.location.href = path

    $(".index-filter select").on "change", (e) =>
      selected = $(".index-filter select option").filter () ->
        @selected
      params = []
      $.each selected, () -> 
        params.push([@getAttribute("name"), @getAttribute("value")])
      path = "/films?" + params.map(([key, val]) => "#{key}=#{val}").join("&")
      window.location.href = path

app/views/films/new.html.slim
h1 New film

== render "form", film: @film

br

div
  = link_to "Back to films", films_path

app/views/films/new_recommendation.html.slim
a href=films_path back to films
br
br
form action=submit_film_recommendation_path method="POST"
  input type='hidden' name='authenticity_token' value=form_authenticity_token
  input type='text' name='sender' placeholder='your name'
  br
  textarea name='message' placeholder='your recommendation / request here' style='width: 500px'
  br
  input type='submit' value='Send'

app/views/films/show.html.slim
=< link_to "Back to films", films_path

p style="color: green" = notice

.film-show
  .film-box style="background: url('#{@film.image_url}')"

  .description-tags
    .film-title-bar
      .content
        / img.poster-img src=@film.image_url
        / a href=film_path(film) = @film.name
        p.film-name = @film.name

        - year = @film.year.present? ? @film.year : "???"

        p
          a href=films_path(director: @film.director) = @film.director
          span = " (#{@film.year})"
        p
          a href=letterboxd_link(@film.name) (View On Letterboxd)
    p.description = @film.description

    - if @film.tags.none?
      b No tags yet
      br
      br
    - @film.tags.each do |tag|
      a.tag href=films_path(tag: tag.name) = tag.name  

    br
    br
    form action=tags_path(film: @film) method='POST'
      div
        input type='hidden' name='authenticity_token' value=form_authenticity_token
        input type='hidden' name='film_id' value=@film.id
        input#tags-autocomplete type='text' name='name'
        input type='submit' value='Add Tag'

  br
  br
  .files
    - if @files[:video].any?
      .watch-link
          h2
            a href=watch_film_path(@film) Watch in browser with subtitle support

    h3 Files
    - if %i[video unsupported_video subtitle].all? { |key| @files[key].none? }
      h3 No Files
    - else
      - if @files[:video].any?
        h4 Video (browser playback supported)
        ul
          - @files[:video].each do |ext, files|
            - files.each do |file|
              li
                a href=Storage.signed_url(file) = file.name

      - if @files[:unsupported_video].any?
        h4 Video (must be downloaded)
        ul
          - @files[:unsupported_video].each do |file|
            li
              a href=Storage.signed_url(file) = file.name

      - if @files[:subtitle].any?
        h4 Subtitle
        ul
          - @files[:subtitle].each do |file|
            li
              a href=Storage.signed_url(file) = file.name
      - else
        h4 Subtitles: none

  .comments
    strong Comments: 
    - if @film.comments.none?
      b =< "none"
    - else
      - @film.comments.each do |comment|
        ul
          li
            div
              b = "#{comment.author} (#{comment.created_at.strftime("%m/%d/%Y")}): "
              span = comment.content

    br
    br
    form action=comments_path method='POST'
      input type='hidden' name='authenticity_token' value=form_authenticity_token
      input type='hidden' name='film_id' value=@film.id
      input type='text' name='author' placeholder='Your Name'
      br
      textarea name='content' style='width: 500px' placeholder='Your Comment'
      br
      input type='submit' value='Add Comment'

  - if admin?
    br
    .admin-links
      h1 admin
      div
        => link_to "Edit this film", edit_film_path(@film)
        br
        br
        = button_to "Destroy this film", @film, method: :delete



  .hidden = Tag.pluck(:name).to_json

coffeescript:

  $ =>
    tags = JSON.parse($(".hidden").text())
    $("#tags-autocomplete").autocomplete({
      source: tags
    })

app/views/films/show_recommendations.html.slim
ul
  - @recommendations.each do |rec|
    li
      span = "#{rec.sender} (#{rec.created_at.strftime("%m/%d/%Y")}) - #{rec.message}"
      form method="POST" action=destroy_recommendation_path(id: rec.id)
        input type='hidden' name='authenticity_token' value=form_authenticity_token
        input type='submit' value='Destroy'
      br

app/views/films/upload.html.slim
form_tag "#", multipart: true, id: :fileupload do
  label_tag 'File:'
  file_field_tag :upload
  submit_tag 'Upload'

div#progress-bar
  #progress

javascript:
  var files = [];
  $('#fileupload').fileupload({
    dataType: 'json',
    url: '/chunk_upload',
    maxChunkSize: 1000000,
    add: function(e, data) {
      $.each(data.files, function(index, file) {
        #$.ajax({
        #  method: 'post',
        #  dataType: 'json',
        #  url: '/uploads',
        #  data: { filename: file.name },
        #  success: function(res) {
        #    data.formData = res;
        #    files.push(data);
        #  }
        # 	
});
      });
    },
  });

app/views/films/watch.html.slim
/ script src="#{root_url}/videosub.js"

a href=film_path(@film) back   
span &nbsp &nbsp &nbsp &nbsp
b = @film.name
br

- if !@selected_video && @vids.values.flatten.count > 1
	h3 There are multiple video files. Please pick which one to use.
	form action=watch_film_path(@film)
		- @vids.each do |media_type, files|
			- files.each.with_index do |file, idx|
				= radio_button_tag("selected_video", {media_type: media_type, name: file.name}.to_json, idx.zero?, id: file.name)
				label for=file.name = file.name
				br
		br
		input type='submit' value='Use File'
- else
	- if @vids.values.flatten.length == 1
		- type = @vids.keys.first
		- src = Storage.signed_url(@vids.values.flatten.first)
	- if @selected_video
		- type = @selected_video[:media_type]
		- src = Storage.signed_url(@selected_video[:file])
	
	video#video-player type=type src=src controls='true'
		- @subs.each do |sub_file|
			track label=sub_file.name kind='subtitles' src=film_subtitle_file_path(name: sub_file.name) srclang='en'

/ .hidden#sub_files
/   = (@subtitles || []).to_json

/ coffeescript:
/ 	$ =>
/ 		$video = $("#video-player")
/ 		subs = JSON.parse($("#sub_files"))