config/routes.rb
Rails.application.routes.draw do
  root "films#index"
  get "/films", to: "films#index"

  scope "films" do
    get "video_file", to: "films#video_file", as: :film_video_file

    get "films/subtitle_file", to: "films#subtitle_file", as: :film_subtitle_file
    get "films/recommendation", to: "films#new_recommendation", as: :film_recommendation
    post "films/recommendation", to: "films#submit_recommendation", as: :submit_film_recommendation
    get '/recommendations', to: "films#show_recommendations", as: :recommendations
    post '/recommendation/:id/destroy', to: "films#destroy_recommendation", as: :destroy_recommendation

    get "films/upload", to: "films#upload", as: :upload_film
    post "films/chunk_create", to: "films#chunk_create", as: :chunk_create

    resources :films, except: [:new, :create]
    resources :unsynced_films, only: [:index]

    # This is done outside of resources because the :id passed here is actually a string
    # And it can cause issues when part of the URL
    get '/unsynced_film', to: "unsynced_films#show", as: :unsynced_film
    post '/force_create_unsynced_film', to: "unsynced_films#force_create", as: :force_create_film

    get "films/:id/watch", to: "films#watch", as: :watch_film

    # should be a post, but too lazy to convert link to form
    get '/unsynced_films/match', to: "unsynced_films#match_unsynced_film", as: :match_unsynced_film

    resources :tags, only: %i[create show]
    post 'tags/:id/remove', to: 'tags#remove', as: :remove_tag

    resources :comments, only: %i[create]
    post 'comments/:id/remove', to: "comments#remove", as: :remove_comment

    get 'info', to: "application#info", as: :info
  end
end

app/views/layouts/_style.html.erb
<style>
body, html {
    margin: none;
    padding: none;
}

body {
    background-color: black;
    color: white;
}

a {
    color: lightgreen;
}

a:hover {
    color: orange;
}

.admin-nav-link {
    display: inline-block;
    margin: 5px;
}

#jellyfin {
    outline: 1px solid white;
    padding: 1px;
    padding-left: 10px;
    margin-left: 5px;
}

#jellyfin .title {
    color: lightgreen;
    text-decoration: none;
    font-size: 24px;
}

#index-filters {
    outline: 1px solid white;
    padding: 5px;
    margin: 5px;
}

.index-filter {
    background-color: SaddleBrown;
    display: inline-block;
    margin: 0 5px;
}

.filter-title {
    padding: 0 5px;
    display: inline-block;
}

.recommendation-link {
    /*float: right;*/
    font-style: italic;
    background-color: darkgreen;
    color: yellow;
    padding: 2px 5px;
    margin: 5px;
    display: inline-block;
}

.info-link {
    /*float: right;*/
    font-style: italic;
    background-color: darkgreen;
    color: yellow;
    padding: 2px 5px;
    margin: 5px;
    display: inline-block;
}

.box {
    border: 1px solid white;
}

.tags, .files, .description-tags, .admin-links, .comments {
    outline: 1px solid white;
    display: inline-block;
    margin: 5px;
    padding: 5px;
    width: 300px;
    height: 400px;
    float: left; 
    box-sizing: border-box;   
}

.watch-link {
    display: inline-block;
}

.comments, .admin-links {
    width: 890px;
    height: auto;
    padding: 10px;
}

.description-tags {
    width: 600px;
    height: 400px;
    /*display: inline-block;*/
    /*width: 600px;*/
}

.clearfix {
    clear: both:
}

.files {
    /*margin-top: 10px;*/
    width: 890px;
    height: auto;
}

@media only screen and (max-width: 890px) {
    .files, .description-tags, .comments, .admin-links {
        width: 100%;
    }
}

h3 {
    text-decoration: underline;
}

.link-box:hover {
    border: 1px solid gold;
}   

#video-player {
    width: 90vw;
    height: 90vh;
} 

.hidden {
    display: none;
    visibility: hidden;
}

.film-show {
    /*display: inline-block;*/
    /*float: left;*/
    /*display: flex;*/
}

.film-show .description, .film-show .film-title-bar {
    border-bottom: 1px solid white;
    padding-bottom: 10px;
}

/*.film-show .description {
    padding-bottom: 10px;
    border-bottom: 1px solid white;
}*/

.film-box {
    float: left;
    margin: 5px;
    padding: 0px;
    display: inline-block;
    width: 280px;
    height: 400px;
    outline: 1px solid white;
    background-size: 300px !important;
    background-repeat: no-repeat !important;
    position: relative;
}   

.film-box .link-placeholder {
    /*background-color: red;*/
    display: inline-block;
    width: 280px;
    height: 400px;
}

.film-box .link-placeholder:hover {
    cursor: pointer;
    outline: 5px solid orange;
}

.film-box .film-title-bar {
    position: absolute;
    bottom: 0;
    border-top: 2px solid white;
}

.film-title-bar {
    background-color: black;
    color: white;
    width: 100%;
    padding: 0px;
}

.film-title-bar .content p {
    margin: 2px 0 !important;
    padding: none;
}

.film-title-bar .content {
    padding: 3px;
}

.film-title-bar .poster-img {
    width: 100%;
}

.film-title-bar .film-name {
    font-weight: bold;
}

.tag {
    border: 1px solid lightgreen;
    margin-right: 5px;
    margin-bottom: 5px;
    padding: 5px;
    display: inline-block;
    border-radius: 10px;
}

.tag:hover {
    border: 1px solid orange;
    color: orange;
}

.film-title-bar a, .film-title-bar a:visited{
    color: lightgreen;
    text-decoration: none;
}

.film-title-bar a:hover {
    color: orange;
}
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VideoStreamer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%#= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script
        src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
        crossorigin="anonymous"></script>
    <script
        src="https://code.jquery.com/ui/1.13.1/jquery-ui.min.js"
        integrity="sha256-eTyxS0rkjpLEo16uXTS0uVCS4815lc40K2iVpWDvdSY="
        crossorigin="anonymous"></script>  
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-file-upload/4.0.11/jquery.uploadfile.min.js" integrity="sha512-uwNlWrX8+f31dKuSezJIHdwlROJWNkP6URRf+FSWkxSgrGRuiAreWzJLA2IpyRH9lN2H67IP5H4CxBcAshYGNw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link rel='stylesheet' href='https://code.jquery.com/ui/1.13.1/themes/trontastic/jquery-ui.css' />      
  <%= render "layouts/style" %>
  </head>

  <body>
    <% if admin? %>
      <a class='admin-nav-link' href='<%= unsynced_films_path%>'> unsynced films </a>
      <a class='admin-nav-link' href='<%= films_path%>'> Films </a>
      <% if Recommendation.count > 0 %>
        <a class='admin-nav-link' href='<%= recommendations_path%>'> <%= Recommendation.count %> recommendation(s) </a>    
      <% end %>
      <hr>
    <% end %>
    <%= yield %>
  </body>
</html>